export enum Genre {
    Alternative = 'KnvZfZ7vAvv' , 
    "Ballads/Romantic" = 'KnvZfZ7vAve', 
    Blues = 'KnvZfZ7vAvd', 
    "Children's Music" = 'KnvZfZ7vAvk',
    Classical = 'KnvZfZ7vAeJ',
    Country = 'KnvZfZ7vAv6',
    "Dance/Electronic" = 'KnvZfZ7vAvF',
    Folk = 'KnvZfZ7vAva',
    "Hip-Hop/Rap" = 'KnvZfZ7vAv1',
    Holiday = 'KnvZfZ7vAvJ',
    Jazz = 'KnvZfZ7vAvE',
    Latin = 'KnvZfZ7vAJ6',
    "Medieval/Renaissance" = 'KnvZfZ7vAvI',
    Metal = 'KnvZfZ7vAvt',
    "New Age" = 'KnvZfZ7vAvn',
    Other = 'KnvZfZ7vAvl',
    Pop = 'KnvZfZ7vAev',
    "R&B" = 'KnvZfZ7vAee',
    Reggae = 'KnvZfZ7vAed',
    Religious = 'KnvZfZ7vAe7',
    Rock = 'KnvZfZ7vAeA',
    World = 'KnvZfZ7vAeF',
};